Q.1>

In [1]:
def FibonacciN(N):
    list = [0,1]
    for i in range(2,N):
        list.append(list[i-2]+list[i-1])
    return list

print(FibonacciN(10))

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


Control Flow and Loops

Q.2>

In [2]:
list=[x for x in range(1,21)]
Square=[x**2 for x in list]
print(Square)
print('-'*15)
list=[x for x in range(1,11)]
Cube={x : x**3 for x in list}
print(Cube)


[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]
---------------
{1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216, 7: 343, 8: 512, 9: 729, 10: 1000}


List and Dictionary Comprehension

Q.3>

In [3]:
import pandas as pd
D = {'Name': pd.Series(['Ayush', 'Vineet', 'Gukesh', 'Mayank', 'Raj']),
     'Age': pd.Series([18,19,20,21,22]),
     'Score': pd.Series([65,70,75,80,85])
     }
Df1 = pd.DataFrame(D)
Df1.to_csv('data.csv', index = False)
Df2 = pd.read_csv('data.csv')
Df3 = Df2.loc[Df2['Score']>75]
Df3

Name  Age  Score
3  Mayank   21     80
4     Raj   22     85

File Handling

Q.4>

In [4]:
import numpy as np
arr = np.random.randint(10,100,25)
print(arr)
print('MAX : ', arr.max(), 'with index : ', np.where(arr == arr.max())[0])
print('MIN : ', arr.min(), 'with index : ', np.where(arr == arr.min())[0])
print(np.where(arr%2!=0, -1, arr))

[71 21 78 87 66 52 51 15 31 85 47 80 96 89 32 92 88 63 37 83 74 63 45 83
 61]
MAX :  96 with index :  [12]
MIN :  15 with index :  [7]
[-1 -1 78 -1 66 52 -1 -1 -1 -1 -1 80 96 -1 32 92 88 -1 -1 -1 74 -1 -1 -1
 -1]


Array Operations

Q.5>

In [5]:
arr = np.random.rand(5,5)
print(arr)
print('-'*15)
print(np.diag(arr))
print('-'*15)
print(np.sum(arr[np.triu_indices(arr.shape[0], k = 1)]))

[[0.88990917 0.44860706 0.77491297 0.52629624 0.19025327]
 [0.67401145 0.98313075 0.78156899 0.40309412 0.59183913]
 [0.70984985 0.02700472 0.52957338 0.01456078 0.69328493]
 [0.55949667 0.6002581  0.23663583 0.04575179 0.77691615]
 [0.9271188  0.68500488 0.48027219 0.79618544 0.66193401]]
---------------
[0.88990917 0.98313075 0.52957338 0.04575179 0.66193401]
---------------
5.201333653286347


Matrix Manipulation

Q.6>

In [6]:
arr = np.random.rand(3,4,5)
print(arr.dtype)
print('-'*15)
k = arr.mean()
l = np.median(arr)
m = arr.std()
print(k)
print('-'*15)
print(l)
print('-'*15)
print(m)
print('-'*15)
n = [(x-k)/m for x in arr]
np.array(n)
print(n)



float64
---------------
0.4637707243144851
---------------
0.42817161629400696
---------------
0.27086609389962946
---------------
[array([[ 0.63551614, -0.12630474,  0.3745467 ,  0.4160662 ,  0.64831715],
       [ 0.75179718, -0.23772662, -0.99255961, -0.85041985,  1.46303446],
       [ 0.47268067, -0.92253313,  1.6726845 , -1.52926245,  1.12362238],
       [ 0.7021655 , -0.36955841,  0.86571841, -0.21542715, -1.43100385]]), array([[ 1.7428024 , -0.12008716,  0.75964109,  0.65396841, -0.92312584],
       [-0.41441615, -1.28601882, -0.71308123,  1.89157629, -0.19364551],
       [ 1.05756689, -1.08212741, -0.09619771,  0.40713055, -1.25969141],
       [-0.4835836 , -1.23780126,  1.97398481, -1.31923938,  1.91397824]]), array([[ 0.10777082,  0.73175936, -0.80617917,  1.10971553,  0.7870421 ],
       [ 1.05944121, -0.72709496, -1.42732732, -0.17819418, -0.46506381],
       [-1.55510991, -1.50933802, -0.17495096,  1.22481759,  0.068258  ],
       [-0.51003192, -0.13654919, -0.99975417, -1.

Satistical Functions

Q.7>

In [7]:
arr1 = np.random.rand(4,4)
arr2 = np.random.rand(4,1)

result = arr1+arr2

print(result)

[[1.61350806 1.64167086 1.32798644 1.68958045]
 [1.00330687 0.51468282 0.30346971 1.01803602]
 [0.89208997 1.03691458 1.16073516 0.41064763]
 [0.07727108 0.22381658 0.5074674  0.33530115]]


Broaadcasting and indexing

Q.8>

In [8]:
list = {'Product' : pd.Series(['Pen', 'Pencil', 'Eraser', 'Sharpner', 'Copy', 'Book', 'Scale', 'Compass']),
        'Price' : pd.Series([10,5,5,5,50,100,10,20]),
        'Quantity' : pd.Series([5,5,1,1,6,5,1,1])}
DF1 = pd.DataFrame(list)
DF1['Total Value'] = DF1['Price']*DF1['Quantity']
DF1.sort_values(by = 'Total Value', ignore_index = True)


Product  Price  Quantity  Total Value
0  Sharpner      5         1            5
1    Eraser      5         1            5
2     Scale     10         1           10
3   Compass     20         1           20
4    Pencil      5         5           25
5       Pen     10         5           50
6      Copy     50         6          300
7      Book    100         5          500

DataFrame Creation and Basic Operations

Q.9>

In [9]:
DF2 = pd.read_csv(r'C:\Users\jeetr\OneDrive\Desktop\JeetrajGupta_230507\titanic.csv')
DF3 = DF2[DF2['Age']<18]
print(DF3)
DF4 = DF2[(DF2['Sex'] == 'female') & (DF2['Survived'] == 1)]
DF4


     PassengerId  Survived  Pclass                                     Name  \
7              8         0       3           Palsson, Master. Gosta Leonard   
9             10         1       2      Nasser, Mrs. Nicholas (Adele Achem)   
10            11         1       3          Sandstrom, Miss. Marguerite Rut   
14            15         0       3     Vestrom, Miss. Hulda Amanda Adolfina   
16            17         0       3                     Rice, Master. Eugene   
..           ...       ...     ...                                      ...   
850          851         0       3  Andersson, Master. Sigvard Harald Elias   
852          853         0       3                  Boulos, Miss. Nourelain   
853          854         1       1                Lines, Miss. Mary Conover   
869          870         1       3          Johnson, Master. Harold Theodor   
875          876         1       3         Najib, Miss. Adele Kiamie "Jane"   

        Sex   Age  SibSp  Parch    Ticket     Fare 

PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
8              9         1       3   
9             10         1       2   
..           ...       ...     ...   
874          875         1       2   
875          876         1       3   
879          880         1       1   
880          881         1       2   
887          888         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
..                                                 ...     ...   ...    ...   
874              Abelson, Mrs. Samuel (Hannah Wizosky)  female  28.0      1   
875                   Najib, Miss. Adele Kiamie "Jane"  female  15.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   

     Parch            Ticket     Fare Cabin Embarked  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
8        2            347742  11.1333   NaN        S  
9        0            237736  30.0708   NaN        C  
..     ...               ...      ...   ...      ...  
874      0         P/PP 3381  24.0000   NaN        C  
875      0              2667   7.2250   NaN        C  
879      1             11767  83.1583   C50        C  
880      1            230433  26.0000   NaN        S  
887      0            112053  30.0000   B42        S  

[233 rows x 12 columns]

Data Filtering

Q.10>

In [10]:
DF5 = pd.read_csv(r'C:\Users\jeetr\OneDrive\Desktop\JeetrajGupta_230507\IRIS.csv')
print(DF5.groupby('species').mean()['petal_length'])
print('-'*15)
print(DF5.groupby('species').mean()['sepal_width'])

species
Iris-setosa        1.464
Iris-versicolor    4.260
Iris-virginica     5.552
Name: petal_length, dtype: float64
---------------
species
Iris-setosa        3.418
Iris-versicolor    2.770
Iris-virginica     2.974
Name: sepal_width, dtype: float64


Groupby Operations

Q.11>

In [11]:
list = {'ONE' : pd.Series([1,2,np.nan,4,5]),
        'TWO' : pd.Series([6,7,8,9,np.nan]),
        'THREE' : pd.Series([11,12,13,np.nan,15])}
DF6 = pd.DataFrame(list)
k = DF6['ONE'].mean()
l = DF6['TWO'].mean()
m = DF6['THREE'].mean()
DF6['ONE'] = DF6['ONE'].fillna(k)
DF6['TWO'] = DF6['TWO'].fillna(l)
DF6['THREE'] = DF6['THREE'].fillna(m)
DF6

ONE  TWO  THREE
0  1.0  6.0  11.00
1  2.0  7.0  12.00
2  3.0  8.0  13.00
3  4.0  9.0  12.75
4  5.0  7.5  15.00

Handling Missing Values

Q.12>

In [12]:
arr1 = {'Id' : pd.Series([101,102,103,104,105]),
        'Name' : pd.Series(['Ayush', 'Vineet', 'Gukesh', 'Mayank', 'Raj'])
        }
arr2 = {'Id' : pd.Series([101,102,103,104,105]),
        'Score' : pd.Series([65,70,75,80,85])
        }
DF7 = pd.DataFrame(arr1)
DF8 = pd.DataFrame(arr2)

DF9 = pd.merge(DF7, DF8, on = 'Id')

DF9

Id    Name  Score
0  101   Ayush     65
1  102  Vineet     70
2  103  Gukesh     75
3  104  Mayank     80
4  105     Raj     85

Merging DataFrames